### ISSUE TITLE
Libraries

### ISSUE THREAD

**Issue by HDTVSWE** [freshollie/MonkeyboardAndroidRadioApp#1]
Hi,
I am trying to setup the Project in B4A, but it takes forever to find all the needed libraries. Could you pls share the needed libraries?

Regards 
Silvester

**Comment by freshollie** [comment]
Ah yeah. Will do.

**Comment by freshollie** [comment]
I have added a list of the required libraries to the readme. I will add the libraries to the folder when I get home if you can't find them that is.

**Comment by HDTVSWE** [comment]
Thanks!

**Comment by HDTVSWE** [comment]
I cant find the "inifiles" library, any suggestion where Í can find it?

**Comment by freshollie** [comment]
I will post all the required libraries when when I can.

**Comment by freshollie** [comment]
Add library dependencies added to repository
