### ISSUE TITLE
Volume control from head unit

### ISSUE THREAD

**Issue by thnilsen** [freshollie/MonkeyboardAndroidRadioApp#3]
It looks like there's a bug with the handleSetVolumeRequest() function in RadioplayerService.java. The code segments in this function is never executed when using the volume control on the device, so the volume always stays at the default level. 

When part of the code in the function is commented out it works as expected. 
```
  public void handleSetVolumeRequest(final int newVolume) {
        //handleAction(
        //        new Runnable() {
        //            @Override
         //           public void run() {
                        volume = newVolume;
                        radio.setVolume(volume);
                        saveVolume();
                    //}
               // }
        //);
    }
```

**Comment by freshollie** [comment]
What's the log error?

**Comment by thnilsen** [comment]
The two Log.d() lines was just used while troubleshooting the issue to see if the code ever got called.

**Comment by freshollie** [comment]
Sorry, I read this wrong. Could you explain the issue in a little more detail. Do you mean the volume buttons on the device don't change the volume? I know that handle set volume works on my testing for setting the volume.

**Comment by thnilsen** [comment]
With the setting "Headunit Controller Input" enabled, the physical volume up/down buttons on the device does not interact with the volume controller in the app. It tries to to reduce/increase the volume, but the saveVolume() function is never triggered. 

When testing the latest code on AVD using both 4.x and 5.x devices, they all show the same issue. By commenting out part of the saveVolume() function as seen in the first post it works as expected.

**Comment by freshollie** [comment]
Just want to update you on this. The volume will only change if the radio is connected. I don't know why this functionality would need to be changed.

**Comment by freshollie** [comment]
Scratch that, updated this
